#define CMD_PWR_ON		0
#define CMD_PWR_OFF		1
#define CMD_RESET		2
#define CMD_NMI			3
#define CMD_GET_PWR		4
#define CMD_GET_TEMP	5
#define CMD_GET_3V3		6
#define CMD_GET_5V		7
#define CMD_GET_12V		8
#define CMD_GET_BAT		9
